"""Write WORLD_MAP place icons + js/maps/worldMapVisuals.js.

Does not regenerate allGrids.js. Re-run after PlaceType world-map colours change:

    python tools/gen_world_map_visuals.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import convert_maps as cm

HTML = Path(__file__).resolve().parents[1]
ICON_DIR = HTML / "assets" / "map" / "icons"
OUT_JS = HTML / "js" / "maps" / "worldMapVisuals.js"


def main() -> None:
    base_colours = cm.parse_base_colours(
        (cm.JAVA_SRC / "com" / "lilithsthrone" / "utils" / "colours" / "BaseColour.java").read_text(
            encoding="utf-8", errors="replace"
        )
    )
    colours = cm.parse_preset_colours(
        (cm.JAVA_SRC / "com" / "lilithsthrone" / "utils" / "colours" / "PresetColour.java").read_text(
            encoding="utf-8", errors="replace"
        ),
        base_colours,
    )
    places = cm.parse_global_place_types(
        cm.PLACETYPE.read_text(encoding="utf-8", errors="replace"), colours
    )
    ICON_DIR.mkdir(parents=True, exist_ok=True)
    visuals = {}
    copied = 0
    missing = []
    for pid, info in sorted(places.items()):
        color = info.get("colourHex") or "#b3b3b3"
        background = info.get("backgroundHex") or color
        visual = {"background": background, "color": color}
        src = None
        if info.get("svg"):
            rel = info["svg"].replace("/", "\\") + ".svg"
            candidate = cm.JAVA_MAPS / rel
            if not candidate.exists():
                candidate = cm.HTML_MAP_ASSETS / rel
            if candidate.exists():
                src = candidate
        if src:
            dest = ICON_DIR / (cm.js_ident(pid) + ".svg")
            dest.write_text(
                cm.recolor_svg(src.read_text(encoding="utf-8", errors="replace"), color),
                encoding="utf-8",
            )
            visual["icon"] = "assets/map/icons/" + dest.name
            copied += 1
        else:
            missing.append(pid)
        visuals[pid] = visual

    lines = [
        "/* Generated by tools/gen_world_map_visuals.py — world-map icons only. */",
        "(function () {",
        "  window.LT = window.LT || {};",
        "  LT.placeVisuals = LT.placeVisuals || {};",
        "  var extra = " + json.dumps(visuals, ensure_ascii=False) + ";",
        "  Object.keys(extra).forEach(function (id) {",
        "    LT.placeVisuals[id] = extra[id];",
        "  });",
        "})();",
        "",
    ]
    OUT_JS.write_text("\n".join(lines), encoding="utf-8")
    print("World-map place types:", len(visuals))
    print("Icons written:", copied)
    print("Wrote", OUT_JS, "({:.1f} KB)".format(OUT_JS.stat().st_size / 1024))
    if missing:
        print("No icon:")
        for pid in missing:
            print("  ", pid)


if __name__ == "__main__":
    main()
